### ISSUE TITLE
Clicking "Sign Up" button logs you in

### ISSUE THREAD

**Issue by khadijah-coakley** [The-Wildfyre-Group/pin#18]
When you are logged out, clicking any “Sign Up”  button at the end of many of the public facing home pages automatically logs you in and take you to a page that says -- “You are already logged in”. A little confusing/inefficient. Perhaps this should take you to your control panel page? Or to the actual sign-up/login page? I think this is related to a bug with being able to logout in general.

**Comment by reignmaster** [comment]
This is fixed.....was pertaining to the issue without logout button but now works properly
