### ISSUE TITLE
Company Account - character min/max deal/summary 

### ISSUE THREAD

**Issue by khadijah-coakley** [The-Wildfyre-Group/pin#52]
We should validate for a character min and max for the "deal summary" and "deal details". This will ensure that investors are provided with sufficient information pertaining to the deal and as well that there are reasonable amounts of content provided for these sections.

**Comment by reignmaster** [comment]
Added a ma characacter limit of 3000.  The field also is requred.  Should I place a min character limit of maybe 50?  It is currently as least 1 character.
