### ISSUE TITLE
Videos Are Not Listed In Alphabetical Order

### ISSUE THREAD

**Issue by eloniat29** [The-Wildfyre-Group/pin#53]
Videos should be listed in Alphabetical Order.

**Comment by reignmaster** [comment]
what page exactly?  The education page inside of the portal? or one of the external pages?

**Comment by eloniat29** [comment]
Sorry, that was a message for training on github, you can delete...

Elonia

Elonia Y. Taylor, Operations Manager
Playbook Investors Network, LLC
1111 West Mockingbird Ln., Suite 1050
Dallas, TX 75248
Tel 214.253.2344| Fax 214.231.0672
email: etaylor@playbookinvestorsnetwork.com
web: www.playbookinvestorsnetwork.com
Twitter:  pbinet1

**Comment by reignmaster** [comment]
ok
