### ISSUE TITLE
Company Profile - Mobile (SMS) Number

### ISSUE THREAD

**Issue by khadijah-coakley** [The-Wildfyre-Group/pin#56]
Why are we asking for a cell number vs. business line? Why is “SMS” mentioned, typically refers to text messages - are they receiving a text. Should we just include business phone and "mobile" number.

**Comment by reignmaster** [comment]
It is probably best that we have business phone number as well as SMS number.  I have added this parameter in the contact info section.  Should we add (or replace sms) this parameter in the registration as well?

**Comment by khadijah-coakley** [comment]
I think the reference to SMS could potentially be a little confusing or less clear. What are your thoughts on using "cell phone or mobile"...if we want to include the reference to SMS in the info hover/popover (I think this is already the case) we can do that if needed.

**Comment by reignmaster** [comment]
Business Phone parameter added.
Also I changed SMS phrasing to "Mobile (Cell) Number".
