### ISSUE TITLE
Company profile - “Best Way to Contact”, make drop-down with suggested prompts

### ISSUE THREAD

**Issue by khadijah-coakley** [The-Wildfyre-Group/pin#58]
We should make this a drop-down with suggested prompts when convenient.

**Comment by reignmaster** [comment]
a dropdown isn't a bad option....lets discuss this with the team.

**Comment by eloniat29** [comment]
I am in agreement that a drop down would be good.

**Comment by reignmaster** [comment]
Done.
Options are:  Email, Business Phone, Cell Number.
Let me know if we should have different terminology.
